services:
  - type: web
    name: compta-app
    env: python
    buildCommand: ""
    startCommand: uvicorn run:app --host=0.0.0.0 --port=8000
    runtime: python
    region: oregon  # ou frankfurt, selon ta localisation
    plan: free
    build:
      envVars:
        - key: PYTHON_VERSION
          value: 3.11.9
    envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 8000
